default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: your_database
  host: <%= ENV['DATABASE_HOST'] %> # Or load from .env

# Load local config if it exists
<%= File.exists?(Rails.root.join("config/database.yml.local")) ? File.read(Rails.root.join("config/database.yml.local")) : '' %>
